"""
Pydantic schemas defining structured outputs across all domain assistants.
Enforces strict type contracts between LLM generation, deterministic engines, and frontend cards.
"""

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Global Envelope & Common Schemas
# ---------------------------------------------------------------------------

class StructuredMessageResponse(BaseModel):
    """Base envelope for any structured response sent to frontend."""
    domain: Literal["education", "finance", "healthcare", "cooking", "general"]
    assistant: str
    text_summary: str = Field(description="Natural language summary or voice-ready response")
    structured_data: Dict[str, Any] = Field(default_factory=dict, description="Domain-specific structured payload")


# ---------------------------------------------------------------------------
# Domain 1: Finance Models
# ---------------------------------------------------------------------------

class ExpenseItem(BaseModel):
    category: str = Field(description="e.g. rent, groceries, utilities, debt, entertainment")
    amount: float = Field(ge=0, description="Monthly amount in currency units")


class FinanceExtraction(BaseModel):
    """Data extracted from the user's message before running Python arithmetic."""
    monthly_income: Optional[float] = Field(default=None, ge=0, description="Monthly income if specified")
    current_savings: Optional[float] = Field(default=None, ge=0, description="Total current savings or investments")
    target_savings_goal: Optional[float] = Field(default=None, ge=0, description="Target savings or purchase amount")
    timeframe_months: Optional[int] = Field(default=None, ge=1, description="Target timeframe in months")
    annual_interest_rate_pct: Optional[float] = Field(default=None, ge=0, le=100, description="Annual return/interest rate %")
    debt_amount: Optional[float] = Field(default=None, ge=0, description="Total debt amount if applicable")
    debt_interest_rate_pct: Optional[float] = Field(default=None, ge=0, le=100, description="Debt APR %")
    monthly_debt_payment: Optional[float] = Field(default=None, ge=0, description="Monthly payment toward debt")
    expenses: List[ExpenseItem] = Field(default_factory=list, description="Extracted expense items")
    goal_type: Literal["budget_analysis", "compound_growth", "debt_payoff", "savings_goal", "general_advice"] = "general_advice"


class FinanceMetrics(BaseModel):
    """Deterministic mathematical metrics calculated purely in Python."""
    total_expenses: float = 0.0
    net_savings_monthly: float = 0.0
    savings_rate_pct: Optional[float] = None
    needs_wants_savings_ratio: Optional[Dict[str, float]] = None  # e.g. {"needs": 50, "wants": 30, "savings": 20}
    emergency_fund_months: Optional[float] = None
    projected_balance: Optional[float] = None  # FV after timeframe
    months_to_reach_goal: Optional[int] = None
    months_to_payoff_debt: Optional[int] = None
    total_interest_paid_or_earned: Optional[float] = None


class FinanceQualitative(BaseModel):
    """Qualitative commentary generated by Groq (no numbers invented)."""
    summary: str = Field(description="Executive summary of the financial situation")
    recommendations: List[str] = Field(description="Actionable, step-by-step financial advice")
    risks: List[str] = Field(description="Financial risks or caveats to watch out for")


class FinanceOutput(BaseModel):
    """Complete structured response for the Finance domain."""
    summary: str
    metrics: FinanceMetrics
    recommendations: List[str]
    risks: List[str]
    disclaimer: str = "This analysis is for educational purposes only and does not constitute professional investment, tax, or legal advice."


# ---------------------------------------------------------------------------
# Domain 2: Cooking Models
# ---------------------------------------------------------------------------

class RecipeIngredient(BaseModel):
    name: str = Field(description="Name of the ingredient, e.g. 'all-purpose flour'")
    quantity: float = Field(ge=0, description="Numeric quantity, e.g. 2.0")
    unit: str = Field(description="Measurement unit: 'g', 'cup', 'tbsp', 'tsp', 'ml', 'piece', etc.")
    notes: Optional[str] = None


class RecipeStep(BaseModel):
    step_number: int
    instruction: str
    timer_seconds: Optional[int] = Field(default=None, ge=1, description="Countdown duration in seconds if step requires timing")


class SubstitutionOption(BaseModel):
    original_ingredient: str
    substitute_name: str
    ratio_or_notes: str


class NutritionFacts(BaseModel):
    """Computed deterministically from the static nutrition database."""
    total_calories: float = 0.0
    protein_g: float = 0.0
    carbs_g: float = 0.0
    fat_g: float = 0.0
    fiber_g: float = 0.0
    servings: int = 1
    calories_per_serving: float = 0.0


class CookingRecipe(BaseModel):
    """Structured Recipe output."""
    title: str
    description: str
    prep_time_minutes: int
    cook_time_minutes: int
    servings: int = 2
    difficulty: Literal["easy", "medium", "hard"] = "medium"
    ingredients: List[RecipeIngredient]
    steps: List[RecipeStep]
    substitutions: List[SubstitutionOption] = Field(default_factory=list)
    nutrition: NutritionFacts = Field(default_factory=NutritionFacts)
    chef_tips: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Domain 3: Education Models
# ---------------------------------------------------------------------------

class DiagramNode(BaseModel):
    id: str
    label: str
    description: Optional[str] = None


class DiagramEdge(BaseModel):
    from_node: str
    to_node: str
    label: Optional[str] = None


class DiagramSpec(BaseModel):
    """Structured graph spec for visual rendering on client (Mermaid/SVG)."""
    type: Literal["flowchart", "timeline", "comparison", "hierarchy"]
    title: str
    nodes: List[DiagramNode]
    edges: List[DiagramEdge]


class QuizQuestion(BaseModel):
    question: str
    options: List[str] = Field(min_length=2, max_length=5)
    correct_index: int = Field(ge=0, le=4)
    explanation: str


class EducationOutput(BaseModel):
    """Structured response for Education domain with diagram & quiz."""
    topic: str
    difficulty_level: Literal["beginner", "intermediate", "advanced"] = "beginner"
    explanation_markdown: str
    key_takeaways: List[str]
    diagram: Optional[DiagramSpec] = None
    quiz: List[QuizQuestion] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Domain 4: Healthcare Models
# ---------------------------------------------------------------------------

class SafetyBanner(BaseModel):
    is_emergency: bool = False
    severity: Literal["none", "mild", "moderate", "urgent", "emergency"] = "none"
    banner_message: Optional[str] = None
    action_required: Optional[str] = None
    emergency_contacts: List[str] = Field(default_factory=list)


class HealthcareOutput(BaseModel):
    """Structured response for Healthcare with deterministic safety gate."""
    safety_banner: SafetyBanner
    topic_or_symptoms: str
    general_guidance_markdown: str
    possible_causes_or_context: List[str] = Field(default_factory=list)
    timeline_or_schedule: Optional[DiagramSpec] = None
    precautions: List[str] = Field(default_factory=list)
    when_to_see_doctor: List[str] = Field(default_factory=list)
    disclaimer: str = "This information is for educational purposes only and is not medical advice or diagnosis. Always consult a qualified healthcare provider."
